server:
  port: 8888
spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:file:./h2/org
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false