server:
  port: 8888
spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:file:./h2/org
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
#  cloud:
#    stream:
#      binders:
#        defaultRabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 192.168.0.105
#                port: 5672
#                username: guest
#                password: guest
#      bindings:
#        output:
#          destination: studyExchange
#          content-type: application/json
#          binder: defaultRabbit
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
logging:
  level:
    com.huangda7.serviceprovider: debug
  file:
    path: D:/Log